language: python
dist: focal

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

before_install:
  - env

install:
  - pip install .

before_script:
  - echo "Before script"

script:
  - echo "Script"

notifications:
  email:
    recipients:
      - builds@workflowhub.org
    on_success: change
    on_failure: always
